### ISSUE TITLE
bintray is discontinued

### ISSUE THREAD

**Issue by individual-it** [pact-foundation/pact-cplusplus#1]
![image](https://user-images.githubusercontent.com/2425577/119088410-5d32ca80-ba28-11eb-89f0-016c93aed457.png)

So the "Download Consumer Lib" link is broken

**Comment by mefellows** [comment]
Ah yes, I recently had to move to another provider for a Scala project.

What's the current standard for C++ projects?

**Comment by individual-it** [comment]
any reason not just to place it in github releases?

**Comment by mefellows** [comment]
I think when it was first created this was useful to the customer that requested it, but GH releases seems reasonable to me. I don't know this ecosystem very well so will follow the discussion.

**Comment by uglyog** [comment]
I've moved the repo to JFrog cloud: https://pactfoundation.jfrog.io/ui/packages/conan:%2F%2Fpact_cpp_consumer

I've also updated the release to attach the artefacts to the release.
