### ISSUE TITLE
Are there plans to provide provider support?

### ISSUE THREAD

**Issue by HolyMiss** [pact-foundation/pact-cplusplus#3]

**Comment by mefellows** [comment]
I'm not sure about a provider interface, but you could look at using the [CLI verifier](https://docs.pact.io/implementation_guides/cli/#native-binary-new) for the mean time?

**Comment by uglyog** [comment]
The CLI verifier is probably the best way to test any provider. Unless you are wanting to use a test framework like Google Test?

**Comment by HolyMiss** [comment]
> The CLI verifier is probably the best way to test any provider. Unless you are wanting to use a test framework like Google Test?

yes, I am using the test framework of google test

**Comment by HolyMiss** [comment]
I have a compilation problem on ubuntu18.04.
![image](https://user-images.githubusercontent.com/39044037/154189493-901fa992-42f1-4037-bb1f-374df2f7d70f.png)

**Comment by uglyog** [comment]
Just raise a feature request at https://pact.canny.io/ so it is tracked and can be voted on.

For that error, try adding `openssl/1.1.1m` to your project.

**Comment by HolyMiss** [comment]
> Just raise a feature request at https://pact.canny.io/ so it is tracked and can be voted on.
> 
> For that error, try adding `openssl/1.1.1m` to your project.

Thanks!

**Comment by HolyMiss** [comment]
I modified the conan.py of your project, I added openssl/1.1.1m, and solved the above error. Should you guys fix this?

**Comment by uglyog** [comment]
It's not something we can just fix. Yes, we can update the project to use openssl/1.1.1m, but then when openssl/1.1.1n is released it becomes a problem again
